### PR TITLE
Fix unexpected default return value of tixiGetDoubleElement

### LINKED ISSUE #129: Unexpected default return values if path does not contain data
I have noticed that the function `getDoubleElement(some_path)` will return a float with value 0.0 even if a node does not contain any number-like values. See for instance the following example (I am using the Python interface for Tixi 3.0.3 in Anaconda):

```python
import tixi3.tixi3wrapper as tixiwrapper

CPACS_FILE = 'D150_AGILE_Hangar.xml'

tixi = tixiwrapper.Tixi3()
tixi.open(CPACS_FILE)

xpath = tixi.uIDGetXPath('D150_VAMP_W1_CompSeg1_innerFlap')

# There should be no value to return here
eta = tixi.getDoubleElement(xpath + '/outerShape/innerBorder/etaLE')
print("Path 1:")
print(eta)

# For this path there exists a float value
eta = tixi.getDoubleElement(xpath + '/outerShape/innerBorder/etaLE/eta')
print("Path 2:")
print(eta)
```

This is the XML code at the paths:

```xml
<trailingEdgeDevice uID="D150_VAMP_W1_CompSeg1_innerFlap" xsi:type="trailingEdgeDeviceType">
    <name>D150_VAMP_W1_CompSeg1_innerFlap</name>
    ...
    <outerShape xsi:type="controlSurfaceOuterShapeType">
        <innerBorder xsi:type="controlSurfaceBorderType">
            <etaLE>
                <eta>0.1103</eta>
                <referenceUID>D150_VAMP_W1_CompSeg1_innerFlap</referenceUID>
            </etaLE>
            ...
        </innerBorder>
    </outerShape>
    ...
</trailingEdgeDevice>
```

The output from the Python code is

```
Path 1:
0.0
Path 2:
0.1103
```

This is the CPACS file I used: [D150_AGILE_Hangar.zip](https://github.com/DLR-SC/tixi/files/3514917/D150_AGILE_Hangar.zip)

Similarly, if `getTextElement()` is used instead of `getDoubleElement()`, path 1 will return an empty string but path 2 will return `0.1103` as a string. From the documentation I understand that `NULL` should be returned if there is no value to return (I guess the Python equivalent would be `None`). However, this is not the case.

Wouldn't it alternatively be more intuitive to raise an error instead of returning `None`?

### PR DESCRIPTION
**Pull request by joergbrech**
- This fixes #129 
 - Fix documentation of `tixiGetTextElement`, `tixiGetDoubleElement` and `tixiGetIntegerElement`: TiXI can handle elements with both text content and additional child elements.
 - Small API change: `tixiGetDoubleElement` and `tixiGetIntegerElement` return `NO_NUMBER`, if they are called for elements for which the context cannot be interpreted numerically. Previously, they returned 0.0, resp. 0.
 - `tixiGetTextElement` still returns an empty string if the xpath points to an element without textual content.
 - Update Travis Build System to Ubuntu 16.04

### CODE REVIEW

File: tests/webmethods_check.cpp [hunk 1]
```diff
@@ -21,12 +21,7 @@
 
 TEST(WebMethods, curlGetFileToLocalDisk)
 {
-  // create some local dummy file
-  FILE* f = fopen("mytmpfile.sh", "w");
-  fprintf(f, "hello world\n");
-  fclose(f);
-
-  int res = curlGetFileToLocalDisk("file://mytmpfile.sh", "tmp.sh");
+  int res = curlGetFileToLocalDisk("https://raw.githubusercontent.com/DLR-SC/tixi/master/tests/TestData/textfile.txt", "tmp.sh");
```
Comment (rainman110) [inline tests/webmethods_check.cpp]: Is there a problem wirh curl's file protocol support on ubuntu?

Comment (joergbrech) [reply tests/webmethods_check.cpp]: Apparently, curl does not support relative paths in newer versions: https://curl.haxx.se/mail/lib-2018-03/0071.html
