### PR TITLE
Fixed text retreiving with special characters

### LINKED ISSUE #107: Inconsisten handling of special characters in text
Special characters get correctly converted to their XML representation using `addTextElement`.

But when using `getTextElement` one obtains the XML representation...

Example Python code:
```
> from tixiwrapper import Tixi
> t = Tixi()
> doc = t.create('root')
> t.addTextElement('/root','bla','bad < text ! &')
> t.getTextElement('/root/bla')
'bad &lt; text ! &amp;'
```

Not sure if fixing this could break any existing applications, though.

### PR DESCRIPTION
**Pull request by rainman110**
Libxml automatically unescapes special characters, if we use the function ``xmlNodeGetContent``.

Before this fix, getting a text element "/root/c" was using another function ``xmlNodeListGetString`` as ``/root/c`` is not the text element in an XPATH meaning. The correct path to the text element would have been ``/root/c/text()``.

To be consistent with tixi's behaviour, I now check whether ``/root/c`` contains only one text element. If this is the case, I return the node content via ``xmlNodeGetContent``.

Fixes #107

### CODE REVIEW

**Comment by rainman110** [comment]
@joergbrech Can you please verify this?

File: src/tixiImpl.c [hunk 1]
```diff
@@ -845,11 +846,15 @@ DLL_EXPORT ReturnCode tixiGetTextElement(const TixiDocumentHandle handle, const
...
-    char *textPtr = NULL;
+    xmlChar *textPtr = NULL;
 
-    if (!xmlNodeIsText(element)) {
+    nChilds = getChildNodeCount(element);
+    if (!xmlNodeIsText(element) && nChilds > 1) {
         textPtr = (char *) xmlNodeListGetString(document->docPtr, element->children, 0);
     }
+    else if(!xmlNodeIsText(element) && nChilds == 1 && xmlNodeIsText(element->children)) {
+        textPtr = (char *) xmlNodeGetContent(element->children);
```
Comment (joergbrech) [inline src/tixiImpl.c:856]: According to to the TiXI documentation, 

> Returns the text content of the element specified by elementPath in the
  document specified by handle. If elementPath does not refer to an element with
  textual content, an empty string is returned.

an empty string should be returned if an element does not have textual content. I believe this line breaks this. You can verify this by changing `tests/TestData/etxtelements.xml` to 

```xml
<root>
    <a>Text</a>
    <b>Text1<c>Text2</c>Text3</b>
    <d><e>Text4</e></d>
</root>
```

and adding the lines 

```cpp
EXPECT_EQ(SUCCESS, tixiGetTextElement(documentHandle, "/root/d", &text));
EXPECT_STREQ("", text);
```

to the any test fixture in `textelements_check.cpp`. The Test succeeds on `master`, but fails on this branch.

Comment (rainman110) [reply src/tixiImpl.c:856]: Good catch!

**Comment by rainman110** [comment]
@joergbrech Should be fixed now

**Comment by rainman110** [comment]
Wait... I can make the code better

**Comment by rainman110** [comment]
I forced push some changes. The if / else statements are simpler now

**Comment by joergbrech** [comment]
LGTM!

**Comment by rainman110** [comment]
I'll merge, when the build is done
